### ISSUE TITLE
Sizing issues

### ISSUE THREAD

**Issue by bfred-it** [shakiba/svgexport#3]
If I don't specify a size, the output will be 400x300

If I specify `119:119`, the size will be correct, but the image is empty

If I specify `0:0:119:119`, the output is correct.

Test SVGs: http://cl.ly/ZEsx

**Comment by shakiba** [comment]
First, I suspect either you are using an old version svgexport or the svg files you have shared are not exactly those you are using. Anyway, please make sure you are using the latest version of svgexport or just reinstall it:
```
npm install svgexport -g
```

Passing only `119:119` parameter is an edge case, because it matches both *input viewbox* and *output size* parameter pattern, in this case it will be used for *output size*, and *input viewbox* will be derived from the svg file. If you want `119:119` to be used as *input viewbox* instead, you need to specify *output size* too, for example just set it as `1x`, for example:
```
svgexport input.svg output.png 119:119 1x
```

But `0:0:119:119` only matches *input viewbox* pattern and then *output size* will inherit those values.

Generally you don't need to specify *input viewbox* if it can be derived from svg file.

**Comment by bfred-it** [comment]
I found and installed svgexport just before trying it, so the version is the latest one. I followed the usage instructions and only entered the output size as instructed.

Anyway, your example works, but I'm repeating information already included in the SVG. My question really is: can svgexport automatically detect the size for the width/height/viewBox attributes?

**Comment by bfred-it** [comment]
I doublechecked and it seems like it only works that way with "output.svg", not "original.svg"

**Comment by shakiba** [comment]
Yes it can detect svg size but it fails on `original.svg` because its `width`/`height` are specified as `119px` instead of just `119`, but both are correct, I should fix it.

Temporary as a work around you can edit `original.svg` files and set `width`/`height` to `119` without `px` (only on `svg` tag).

**Comment by shakiba** [comment]
I guess I have fixed it now, please update to 0.1.14 and give it a try.

**Comment by bfred-it** [comment]
It does work, thanks!

**Comment by shakiba** [comment]
Thanks for reporting!
