### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by SamyPesse** [shakiba/svgexport#7]
On windows, I'm getting an ENOENT error when trying to load phamtomjs. I think this is because on Windows, we need to run `phantomjs.cmd` instead.

**Comment by shakiba** [comment]
I just published an update, I have replaced hard-coded phantomjs bin path with `require('phantomjs').path`, it may fix this issue, please try it. I don't have a Windows installation ready to use, but if it doesn't work then I will prepare one, probably in one or two days.

**Comment by SamyPesse** [comment]
I'm going to test it. It will be nice to add some basic unittests with Travis (for Linux and OS X) and Appveyor (for Windows, free for open source).

**Comment by SamyPesse** [comment]
This is not working, but not the same error,

This time, svgexport doesn't crash and return an exit code 0 but stdout is:

```SyntaxError: Unable to parse JSON string```

I'm debugging this issue and will keep you updated :)

**Comment by shakiba** [comment]
Thanks, I'm trying Travis.

**Comment by SamyPesse** [comment]
The issue was comign from GitBook, it's now working fine except one svg that raise an error with phamtomjs (only on windows):  
```
TypeError: 'undefined' is not a function (evaluating 'el.getBBox()')

TypeError: 'null' is not an oject (evaluating 'input.height')
```

**Comment by shakiba** [comment]
I added svgeport to [Travis](https://travis-ci.org/shakiba/svgexport) and [Appveyor](https://ci.appveyor.com/project/shakiba/svgexport), thanks for your suggestion! There are some issues with running child process on Appveyor.

For your latest issue I published another update, it may fix it. Otherwise see [here](https://github.com/akoenig/gulp-svg2png/issues/8), in short your svg should start with`<?xml version="1.0" encoding="UTF-8"?>`.
